import "./mitor.scss";
import "@stephane888/wbu-atomique/js/bootstrap/all.js";

 import "./mitor-faq/faq"
import "./mitor-core-value/core-value"
import "./navbar/navbar";
import "./mitor-hero/top";
 import "./mitor-hero-2/top";
 import "./mitor-services/service";
import "./mitor-card-blog/service.js";
 import "./mitor-card-img/top";
import "./mitor-card-image/card-img";
import "./mitor-project-tabs/service";
 import "./mitor-testimony/testimony";
 import "./top-project-galery/service";
import "./mitor-footer/footer";
import "./mitor-pricing/pricing";
import "./mitor-overview/top";
import './mitor-team/team'
import "./mitor-footer/footer";
import "./mitor-pricing/pricing";
import "./mitor-overview/top";
import './mitor-team/team'
//import "./mitor-blog/blogs"
import './mitor-404/404'
import "./mitor-contact-hero/hero"
import "./mitor-coming-soon/mitor-coming-soon";
