import './header/header'
import './welcome-section/welcome'
import './security-info-section/security.js'
import './locksmith-services/lock.js'
import './team-section/team'
import './products-section/product'
import './services-overview/overview'
import './footer/footer'