import "@stephane888/wbu-atomique/scss/bootstrap-all.scss";
import "@stephane888/wbu-atomique/js/bootstrap/all.js";
import 'https://unpkg.com/swiper@8/swiper-bundle.min.js'
import "https://code.jquery.com/jquery-3.3.1.slim.min.js"
import "https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
import "https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
import './header/header'
//import './welcome-section/welcome'
//import './security-info-section/security.js'
//import './locksmith-services/lock.js'
//import './team-section/team'
//import './products-section/product'
//import './services-overview/overview'
//import './footer/footer'