import "./restoRed.scss";
import "./redModel/redModel";
 import "./sectionService/sectionService"
 import "./sectionReservation/sectionReservation"
 import "./sectionMenuSwiper/sectionMenuSwiper"
 import "./sectionPopular/sectionPopular"
 import "./sectionTeam/sectionTeam"
 import "./sectionBlogs/sectionBlogs"
 import "./restoRedFooter/restoRedFooter"